version: "3.8"

services:
  postgres:
    image: postgres:14
    env_file:
      - ./.env.pgsql
    expose:
      - "5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    labels:
      - "traefik.enable=false"
    networks:
      - postgres

volumes:
  postgres-data:

networks:
  postgres:
