version: "3.8"

services:
  svc:
    image: meysam81/dockercon2022-svc-1
    build: .
    restart: unless-stopped
    env_file:
      - ./deploy/docker.env
    environment:
      - PORT=8000
      - DEBUG=1
      - APP_PREFIX=${APP_PREFIX}
    volumes:
      - "./app:/service/app:ro"
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.svc${SVC_ID}.rule=Host(`svc.dockercon2022.com`) && PathPrefix(`${APP_PREFIX}`)"
